# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gatsby.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          SPACE_ID: ${{ secrets.SPACE_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --prefix-paths
